//! **CLI Scaffold** — Project scaffolding and code generation.
//!
//! `killer init`, `killer generate component`, `killer build`, etc.
//! Generates project templates, component boilerplate, route configs, test files.
//! Equivalent to Angular CLI / Create React App / Vite CLI.

use std::collections::HashMap;

// ══════════════════════════════════════════════════════════════════════════════
// Project template
// ══════════════════════════════════════════════════════════════════════════════

/// Template types for project initialization.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum ProjectTemplate {
    Minimal,
    App,
    Dashboard,
    Fullstack,
    Library,
}

/// Project configuration.
#[derive(Debug, Clone)]
pub struct ProjectConfig {
    pub name: String,
    pub template: ProjectTemplate,
    pub features: Vec<String>,
    pub styling: StylingOption,
    pub testing: bool,
    pub ssr: bool,
    pub router: bool,
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum StylingOption {
    None,
    Css,
    Tailwind,
    MaterialTheme,
}

impl Default for ProjectConfig {
    fn default() -> Self {
        ProjectConfig {
            name: "my-killer-app".into(),
            template: ProjectTemplate::App,
            features: Vec::new(),
            styling: StylingOption::Css,
            testing: true,
            ssr: false,
            router: true,
        }
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// File generator
// ══════════════════════════════════════════════════════════════════════════════

/// A generated file with its path and content.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    pub path: String,
    pub content: String,
}

/// Generate project scaffold files.
pub fn scaffold_project(config: &ProjectConfig) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    let name = &config.name;

    // Main entry
    files.push(GeneratedFile {
        path: format!("{}/src/main.killer", name),
        content: generate_main(config),
    });

    // App component
    files.push(GeneratedFile {
        path: format!("{}/src/app.killer", name),
        content: generate_app_component(config),
    });

    // Config
    files.push(GeneratedFile {
        path: format!("{}/killer.toml", name),
        content: generate_config(config),
    });

    // Router (if enabled)
    if config.router {
        files.push(GeneratedFile {
            path: format!("{}/src/routes.killer", name),
            content: generate_routes(config),
        });
    }

    // Test file (if enabled)
    if config.testing {
        files.push(GeneratedFile {
            path: format!("{}/tests/app_test.killer", name),
            content: generate_test(config),
        });
    }

    // Template-specific files
    match config.template {
        ProjectTemplate::Dashboard => {
            files.push(GeneratedFile {
                path: format!("{}/src/pages/dashboard.killer", name),
                content: generate_dashboard_page(),
            });
        }
        ProjectTemplate::Fullstack => {
            files.push(GeneratedFile {
                path: format!("{}/src/api/server.killer", name),
                content: generate_server(),
            });
            files.push(GeneratedFile {
                path: format!("{}/src/api/routes.killer", name),
                content: generate_api_routes(),
            });
        }
        _ => {}
    }

    // Styling
    if config.styling != StylingOption::None {
        files.push(GeneratedFile {
            path: format!("{}/src/styles/global.css", name),
            content: generate_global_css(config),
        });
    }

    // SSR config
    if config.ssr {
        files.push(GeneratedFile {
            path: format!("{}/src/ssr.killer", name),
            content: generate_ssr_config(),
        });
    }

    // README
    files.push(GeneratedFile {
        path: format!("{}/README.md", name),
        content: format!("# {}\n\nGenerated by `killer init`.\n\n## Quick Start\n\n```\nkiller dev\nkiller build\nkiller test\n```\n", name),
    });

    files
}

fn generate_main(config: &ProjectConfig) -> String {
    let mut code = String::from("// Main entry point\n");
    code.push_str(&format!("// Generated by killer init (template: {:?})\n\n", config.template));
    code.push_str("import \"./app\"\n\n");
    if config.router {
        code.push_str("import \"./routes\"\n\n");
    }
    code.push_str("kfn main() {\n");
    code.push_str("    let app = App()\n");
    code.push_str("    render(app)\n");
    code.push_str("}\n");
    code
}

fn generate_app_component(config: &ProjectConfig) -> String {
    let mut code = String::from("// Root application component\n\n");
    code.push_str("component App {\n");
    code.push_str("    state {\n");
    code.push_str(&format!("        title: \"{}\"\n", config.name));
    code.push_str("        count: 0\n");
    code.push_str("    }\n\n");
    code.push_str("    render {\n");
    code.push_str("        <Column>\n");
    code.push_str("            <Label text={state.title} />\n");
    code.push_str("            <Button label=\"Click me\" @click={state.count = state.count + 1} />\n");
    code.push_str("            <Label text={\"Count: \" + state.count} />\n");
    code.push_str("        </Column>\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    code
}

fn generate_config(config: &ProjectConfig) -> String {
    let mut toml = String::from("[project]\n");
    toml.push_str(&format!("name = \"{}\"\n", config.name));
    toml.push_str("version = \"0.1.0\"\n\n");
    toml.push_str("[build]\n");
    toml.push_str("target = \"web\"\n");
    toml.push_str("minify = true\n");
    toml.push_str("tree_shake = true\n\n");
    if !config.features.is_empty() {
        toml.push_str("[features]\n");
        for f in &config.features {
            toml.push_str(&format!("{} = true\n", f));
        }
    }
    toml
}

fn generate_routes(_config: &ProjectConfig) -> String {
    let mut code = String::from("// Application routes\n\n");
    code.push_str("routes {\n");
    code.push_str("    \"/\" => HomePage\n");
    code.push_str("    \"/about\" => AboutPage\n");
    code.push_str("    \"/settings\" => SettingsPage\n");
    code.push_str("    \"*\" => NotFoundPage\n");
    code.push_str("}\n");
    code
}

fn generate_test(_config: &ProjectConfig) -> String {
    let mut code = String::from("// App tests\n\n");
    code.push_str("test \"app renders\" {\n");
    code.push_str("    let host = TestHost()\n");
    code.push_str("    host.render(App())\n");
    code.push_str("    assert(host.query_by_text(\"Click me\") != null)\n");
    code.push_str("}\n\n");
    code.push_str("test \"counter increments\" {\n");
    code.push_str("    let host = TestHost()\n");
    code.push_str("    host.render(App())\n");
    code.push_str("    host.fire_click(\"btn\")\n");
    code.push_str("    assert(host.query_by_text(\"Count: 1\") != null)\n");
    code.push_str("}\n");
    code
}

fn generate_dashboard_page() -> String {
    "// Dashboard page\n\ncomponent DashboardPage {\n    render {\n        <Dashboard title=\"Admin\">\n            <StatCard title=\"Users\" value=\"1,234\" trend=\"+12%\" />\n            <StatCard title=\"Revenue\" value=\"$42K\" trend=\"+8%\" />\n            <DataGrid columns={[\"Name\", \"Email\", \"Role\"]} />\n        </Dashboard>\n    }\n}\n".into()
}

fn generate_server() -> String {
    "// API server\n\nkfn start_server(port) {\n    let server = HttpServer(port)\n    server.use(cors())\n    server.use(json_parser())\n    import \"./routes\"\n    server.listen()\n}\n".into()
}

fn generate_api_routes() -> String {
    "// API routes\n\napi {\n    GET  \"/api/users\"     => get_users\n    POST \"/api/users\"     => create_user\n    GET  \"/api/users/:id\" => get_user\n}\n".into()
}

fn generate_global_css(config: &ProjectConfig) -> String {
    match config.styling {
        StylingOption::MaterialTheme => "/* Material Design tokens */\n:root {\n    --primary: #1976d2;\n    --secondary: #9c27b0;\n    --error: #d32f2f;\n    --background: #ffffff;\n    --surface: #f5f5f5;\n    --spacing: 8px;\n    --radius: 4px;\n}\n\n* { box-sizing: border-box; margin: 0; padding: 0; }\nbody { font-family: 'Roboto', sans-serif; }\n".into(),
        _ => "/* Global styles */\n:root {\n    --primary: #0070f3;\n    --background: #ffffff;\n}\n\n* { box-sizing: border-box; margin: 0; padding: 0; }\n".into(),
    }
}

fn generate_ssr_config() -> String {
    "// SSR configuration\n\nssr {\n    mode: \"streaming\"\n    hydrate: true\n    routes: [\"/\", \"/about\"]\n}\n".into()
}

// ══════════════════════════════════════════════════════════════════════════════
// Component generator
// ══════════════════════════════════════════════════════════════════════════════

/// Blueprint for generating a component.
#[derive(Debug, Clone)]
pub struct ComponentBlueprint {
    pub name: String,
    pub props: Vec<(String, String)>, // (name, type)
    pub with_state: bool,
    pub with_lifecycle: bool,
    pub with_test: bool,
}

/// Generate component boilerplate files.
pub fn generate_component(bp: &ComponentBlueprint) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    let name_lower = bp.name.to_lowercase();

    let mut code = format!("// {} component\n\n", bp.name);
    code.push_str(&format!("component {} {{\n", bp.name));

    if !bp.props.is_empty() {
        code.push_str("    props {\n");
        for (name, typ) in &bp.props {
            code.push_str(&format!("        {}: {}\n", name, typ));
        }
        code.push_str("    }\n\n");
    }

    if bp.with_state {
        code.push_str("    state {\n        loading: false\n    }\n\n");
    }

    if bp.with_lifecycle {
        code.push_str("    on_mount {\n        // Initialize\n    }\n\n");
        code.push_str("    on_unmount {\n        // Cleanup\n    }\n\n");
    }

    code.push_str("    render {\n");
    code.push_str(&format!("        <Column>\n            <Label text=\"{}\" />\n        </Column>\n", bp.name));
    code.push_str("    }\n");
    code.push_str("}\n");

    files.push(GeneratedFile {
        path: format!("src/components/{}.killer", name_lower),
        content: code,
    });

    if bp.with_test {
        let mut test_code = format!("// {} tests\n\n", bp.name);
        test_code.push_str(&format!("test \"{} renders\" {{\n", bp.name));
        test_code.push_str("    let host = TestHost()\n");
        test_code.push_str(&format!("    host.render({}())\n", bp.name));
        test_code.push_str(&format!("    assert(host.query_by_text(\"{}\") != null)\n", bp.name));
        test_code.push_str("}\n");
        files.push(GeneratedFile {
            path: format!("tests/components/{}_test.killer", name_lower),
            content: test_code,
        });
    }

    files
}

/// CLI command representation.
#[derive(Debug, Clone)]
pub enum CliCommand {
    Init(ProjectConfig),
    Generate { kind: String, name: String, options: HashMap<String, String> },
    Build { production: bool },
    Dev { port: u16 },
    Test { filter: Option<String> },
    Lint,
    Format,
}

/// Parse CLI args into a command.
pub fn parse_cli(args: &[&str]) -> Result<CliCommand, String> {
    if args.is_empty() {
        return Err("No command specified. Usage: killer <init|generate|build|dev|test|lint|format>".into());
    }
    match args[0] {
        "init" => {
            let mut config = ProjectConfig::default();
            if args.len() > 1 { config.name = args[1].to_string(); }
            Ok(CliCommand::Init(config))
        }
        "generate" | "g" => {
            if args.len() < 3 { return Err("Usage: killer generate <component|page|service> <name>".into()); }
            Ok(CliCommand::Generate {
                kind: args[1].into(),
                name: args[2].into(),
                options: HashMap::new(),
            })
        }
        "build" => {
            let production = args.iter().any(|a| *a == "--prod" || *a == "--production");
            Ok(CliCommand::Build { production })
        }
        "dev" => {
            let port = args.iter().position(|a| *a == "--port")
                .and_then(|i| args.get(i + 1))
                .and_then(|p| p.parse::<u16>().ok())
                .unwrap_or(3000);
            Ok(CliCommand::Dev { port })
        }
        "test" => {
            let filter = if args.len() > 1 { Some(args[1].to_string()) } else { None };
            Ok(CliCommand::Test { filter })
        }
        "lint" => Ok(CliCommand::Lint),
        "format" | "fmt" => Ok(CliCommand::Format),
        cmd => Err(format!("Unknown command: '{}'. Available: init, generate, build, dev, test, lint, format", cmd)),
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// Tests
// ══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_minimal() {
        let config = ProjectConfig {
            name: "test-app".into(),
            template: ProjectTemplate::Minimal,
            router: false, testing: false, ssr: false,
            ..Default::default()
        };
        let files = scaffold_project(&config);
        assert!(files.iter().any(|f| f.path.contains("main.killer")));
        assert!(files.iter().any(|f| f.path.contains("app.killer")));
        assert!(files.iter().any(|f| f.path.contains("killer.toml")));
        assert!(!files.iter().any(|f| f.path.contains("routes.killer")));
    }

    #[test]
    fn scaffold_with_router() {
        let config = ProjectConfig { router: true, ..Default::default() };
        let files = scaffold_project(&config);
        assert!(files.iter().any(|f| f.path.contains("routes.killer")));
    }

    #[test]
    fn scaffold_fullstack() {
        let config = ProjectConfig {
            template: ProjectTemplate::Fullstack,
            ..Default::default()
        };
        let files = scaffold_project(&config);
        assert!(files.iter().any(|f| f.path.contains("server.killer")));
        assert!(files.iter().any(|f| f.path.contains("api/routes.killer")));
    }

    #[test]
    fn scaffold_dashboard() {
        let config = ProjectConfig {
            template: ProjectTemplate::Dashboard,
            ..Default::default()
        };
        let files = scaffold_project(&config);
        assert!(files.iter().any(|f| f.path.contains("dashboard.killer")));
    }

    #[test]
    fn scaffold_with_ssr() {
        let config = ProjectConfig { ssr: true, ..Default::default() };
        let files = scaffold_project(&config);
        assert!(files.iter().any(|f| f.path.contains("ssr.killer")));
    }

    #[test]
    fn generate_component_basic() {
        let bp = ComponentBlueprint {
            name: "UserCard".into(),
            props: vec![("name".into(), "String".into()), ("age".into(), "Int".into())],
            with_state: true,
            with_lifecycle: true,
            with_test: true,
        };
        let files = generate_component(&bp);
        assert_eq!(files.len(), 2); // component + test
        assert!(files[0].content.contains("component UserCard"));
        assert!(files[0].content.contains("name: String"));
        assert!(files[0].content.contains("on_mount"));
        assert!(files[1].content.contains("UserCard renders"));
    }

    #[test]
    fn parse_cli_init() {
        let cmd = parse_cli(&["init", "my-app"]).unwrap();
        if let CliCommand::Init(config) = cmd {
            assert_eq!(config.name, "my-app");
        } else { panic!("Expected Init"); }
    }

    #[test]
    fn parse_cli_generate() {
        let cmd = parse_cli(&["generate", "component", "Button"]).unwrap();
        if let CliCommand::Generate { kind, name, .. } = cmd {
            assert_eq!(kind, "component");
            assert_eq!(name, "Button");
        } else { panic!("Expected Generate"); }
    }

    #[test]
    fn parse_cli_build_prod() {
        let cmd = parse_cli(&["build", "--prod"]).unwrap();
        if let CliCommand::Build { production } = cmd {
            assert!(production);
        } else { panic!("Expected Build"); }
    }

    #[test]
    fn parse_cli_dev_port() {
        let cmd = parse_cli(&["dev", "--port", "8080"]).unwrap();
        if let CliCommand::Dev { port } = cmd {
            assert_eq!(port, 8080);
        } else { panic!("Expected Dev"); }
    }

    #[test]
    fn parse_cli_unknown() {
        assert!(parse_cli(&["unknown"]).is_err());
    }

    #[test]
    fn parse_cli_empty() {
        assert!(parse_cli(&[]).is_err());
    }

    #[test]
    fn config_has_readme() {
        let files = scaffold_project(&ProjectConfig::default());
        assert!(files.iter().any(|f| f.path.contains("README.md")));
    }
}
