// image_gen.rs — Kala Image & Video Generation Engine
//
// Image generation:
//   kala_generate_image(prompt)                  → image rendered in chat (Pollinations free by default)
//   kala_generate_image(prompt, style)            → style: "photorealistic"|"artistic"|"anime"|"3d"|"sketch"
//   kala_generate_image(prompt, style, size)      → size: "square"|"landscape"|"portrait"|"hd"
//
// Video generation:
//   kala_generate_video(prompt)                   → URL / task ID or guide table
//   kala_generate_video(prompt, duration)         → duration: "5" | "10" (seconds)
//
// Provider routing (in priority order):
//   OPENAI_API_KEY set      → DALL-E 3  (highest quality)
//   STABILITY_API_KEY set   → Stability AI SDXL
//   No key (default)        → Pollinations.ai  (FREE, no key, works immediately, renders inline)
//   RUNWAY_API_KEY set      → Runway Gen-3 Alpha Turbo (video)
//
// Zero extra crates — curl subprocess (same pattern as llm.rs).

use std::process::Command;
use crate::value::Value;
use crate::error::VmError;
use crate::khlm_polyglot::config;

// ─────────────────────────────────────────────────────────────────────────────
// PUBLIC BUILTINS
// ─────────────────────────────────────────────────────────────────────────────

/// kala_generate_image(prompt [, style [, size]]) → String
///
/// Generates an image from a text description.
///
/// Arguments:
///   prompt  — what to generate, e.g. "a sunset over Tokyo in neon lights"
///   style   — "photorealistic" | "artistic" | "anime" | "3d" | "sketch" | "cinematic" | "auto"
///   size    — "square" | "landscape" | "portrait" | "hd"
///
/// Killer:
///   url = kala_generate_image("a city skyline built on glowing Killer code circuits")
///   print(K"Image: {url}")
pub fn builtin_kala_generate_image(args: &[Value]) -> Result<Value, VmError> {
    crate::security::require_llm()?;
    crate::security::require_network()?;
    let prompt = get_str_arg(args, 0, "prompt")?;
    let style  = get_str_arg(args, 1, "style").unwrap_or_else(|_| "auto".into());
    let size   = get_str_arg(args, 2, "size").unwrap_or_else(|_| "square".into());
    Ok(Value::Str(generate_image(&prompt, &style, &size)))
}

/// kala_generate_video(prompt [, duration]) → String
///
/// Generates a short video clip from a text description.
///
/// Arguments:
///   prompt   — scene description
///   duration — "5" or "10" (seconds)
///
/// Killer:
///   result = kala_generate_video("a neon Killer code city at dawn, drone shot", "5")
///   print(result)
pub fn builtin_kala_generate_video(args: &[Value]) -> Result<Value, VmError> {
    crate::security::require_llm()?;
    crate::security::require_network()?;
    let prompt   = get_str_arg(args, 0, "prompt")?;
    let duration = get_str_arg(args, 1, "duration").unwrap_or_else(|_| "5".into());
    Ok(Value::Str(generate_video(&prompt, &duration)))
}

// ─────────────────────────────────────────────────────────────────────────────
// CORE GENERATION
// ─────────────────────────────────────────────────────────────────────────────

pub fn generate_image(prompt: &str, style: &str, size: &str) -> String {
    let (provider, api_key, _model) = get_gen_config();

    // Use configured premium provider if available
    if provider.to_lowercase() == "openai" && !api_key.is_empty() {
        let enhanced = enhance_image_prompt(prompt, style);
        return generate_image_dalle(&enhanced, &api_key, size)
            .unwrap_or_else(|_| generate_image_native_wrapped(prompt, style));
    }
    if provider.to_lowercase() == "stability" && !api_key.is_empty() {
        let enhanced = enhance_image_prompt(prompt, style);
        return generate_image_stability(&enhanced, &api_key, size)
            .unwrap_or_else(|_| generate_image_native_wrapped(prompt, style));
    }

    // Default: Nova Native — pure Rust procedural image synthesis
    // Zero network, zero API keys, instant generation < 10ms
    generate_image_native_wrapped(prompt, style)
}

/// Generate image using the Nova native engine and wrap in Kala chat markdown.
fn generate_image_native_wrapped(prompt: &str, _style: &str) -> String {
    let data_uri = crate::nova_gen::generate_image_native(prompt);
    let prompt_short = &prompt[..prompt.len().min(80)];
    format!(
        "## 🖼️ Kala Created Your Image\n\n\
         ![{ps}]({di})\n\n\
         > ✅ Generated by **Nova Native Engine** · Pure Rust · Zero network · Instant\n\n\
         *Upgrade to DALL-E 3 or Stability AI: `kala_set_llm(\"openai\", \"sk-...\")` then ask again*",
        ps = prompt_short, di = data_uri
    )
}

pub fn generate_video(prompt: &str, duration: &str) -> String {
    let cinematic = enhance_video_prompt(prompt);
    let (provider, api_key, _model) = get_gen_config();

    match provider.to_lowercase().as_str() {
        "runway" if !api_key.is_empty() =>
            generate_video_runway(&cinematic, &api_key, duration)
                .unwrap_or_else(|_| generate_video_native_wrapped(prompt)),
        _ => generate_video_native_wrapped(prompt),
    }
}

/// Native GIF animation — pure Rust, zero network, zero API
fn generate_video_native_wrapped(prompt: &str) -> String {
    let data_uri    = crate::nova_video::generate_video_native(prompt);
    let prompt_short = &prompt[..prompt.len().min(80)];
    format!(
        "## \u{1f3ac} Kala Created Your Animation\n\n\
         ![{ps}]({di})\n\n\
         > \u{2705} Generated by **Nova Video Engine** \u{00b7} Pure Rust \u{00b7} Zero network \u{00b7} Animated GIF\n\n\
         *{} frames \u{00b7} 64\u{00d7}64 \u{00b7} ~14fps \u{00b7} Scene: {}*",
        crate::nova_video::N_FRAMES,
        crate::nova_video::scene_name(prompt),
        ps = prompt_short, di = data_uri
    )
}

/// Generate audio from a prompt
pub fn generate_audio(prompt: &str) -> String {
    generate_audio_native_wrapped(prompt)
}

/// Native WAV synthesis — pure Rust, zero network
fn generate_audio_native_wrapped(prompt: &str) -> String {
    let data_uri     = crate::nova_audio::generate_audio_native(prompt);
    let _prompt_short = &prompt[..prompt.len().min(80)];
    let scene        = crate::nova_audio::scene_name(prompt);
    format!(
        "## \u{1f3b5} Kala Created Your Audio\n\n\
         <audio controls src=\"{di}\" style=\"width:100%;margin:8px 0;border-radius:10px\"></audio>\n\n\
         > \u{2705} Generated by **Nova Audio Engine** \u{00b7} Pure Rust \u{00b7} Zero network \u{00b7} Instant\n\n\
         *Scene: {sc} \u{00b7} 3 seconds \u{00b7} 22050 Hz PCM \u{00b7} Mono*",
        di = data_uri, sc = scene
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Pollinations.ai — FREE default, no API key needed
// ─────────────────────────────────────────────────────────────────────────────

#[allow(dead_code)]
fn url_encode_prompt(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 2);
    for c in s.chars() {
        match c {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '-' | '_' | '.' => out.push(c),
            ' ' => out.push('+'),
            _ => for b in c.to_string().bytes() { out.push_str(&format!("%{:02X}", b)); },
        }
    }
    out
}

#[allow(dead_code)]
fn generate_image_pollinations(prompt: &str, style: &str, size: &str) -> String {
    let enhanced = enhance_image_prompt(prompt, style);
    let encoded  = url_encode_prompt(&enhanced);
    let (w, h): (u32, u32) = match size.to_lowercase().as_str() {
        "landscape" => (1792, 1024),
        "portrait"  => (1024, 1792),
        _           => (1024, 1024),
    };
    let url = format!(
        "https://image.pollinations.ai/prompt/{}?width={}&height={}&nologo=true&model=flux",
        encoded, w, h
    );
    let prompt_short = &prompt[..prompt.len().min(80)];

    // Download image server-side → embed as base64 data URI → always displays inline in chat
    match download_image_as_data_uri(&url) {
        Ok(data_uri) => format!(
            "## 🖼️ Kala Created Your Image\n\n\
             ![{ps}]({di})\n\n\
             > ✅ Generated by Kala · Free · Pollinations Flux model\n\n\
             *Upgrade to DALL-E 3: `kala_set_llm(\"openai\", \"sk-...\")` then ask again*",
            ps = prompt_short, di = data_uri
        ),
        Err(e) => format!(
            "## 🖼️ Image Ready\n\n\
             **[VIEW IMAGE ↗]({url})**\n\n\
             `{url}`\n\n\
             > Pollinations AI · Flux model · via Kala\n\n\
             *(open the link above — {e})*",
            url = url, e = e
        ),
    }
}

/// Download an image from a URL and return it as a base64 data URI.
/// Uses curl (already a dependency) and a temp file — zero extra crates.
#[allow(dead_code)]
fn download_image_as_data_uri(url: &str) -> Result<String, String> {
    if !url.starts_with("https://") {
        return Err("HTTPS required".into());
    }
    // Write to OS temp dir to avoid cluttering the working directory
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs()).unwrap_or(0);
    let tmp = std::env::temp_dir().join(format!("kala_img_{}.bin", ts));
    let tmp_str = tmp.to_string_lossy().to_string();

    // curl -sLk: silent + follow redirects + insecure (bypass SSL cert errors on Windows)
    // --max-time 90: Pollinations AI image generation can take up to 90 seconds
    let status = Command::new("curl")
        .args(["-sLk", "--max-time", "90", "--connect-timeout", "15", url, "-o", &tmp_str])
        .status()
        .map_err(|e| format!("curl not found: {}", e))?;

    if !status.success() {
        let _ = std::fs::remove_file(&tmp);
        return Err(format!("download failed ({})", status));
    }

    let bytes = std::fs::read(&tmp)
        .map_err(|e| { let _ = std::fs::remove_file(&tmp); format!("read: {}", e) })?;
    let _ = std::fs::remove_file(&tmp);

    if bytes.len() < 16 {
        return Err("empty or too-small response".into());
    }

    // Detect MIME type from magic bytes
    let mime = if bytes[0] == 0xFF && bytes[1] == 0xD8 {
        "image/jpeg"
    } else if &bytes[0..4] == b"\x89PNG" {
        "image/png"
    } else if bytes.len() > 5 && &bytes[0..6] == b"GIF89a" {
        "image/gif"
    } else {
        "image/jpeg" // Pollinations always returns JPEG by default
    };

    Ok(format!("data:{};base64,{}", mime, base64_encode(&bytes)))
}

#[allow(dead_code)]
fn base64_encode(bytes: &[u8]) -> String {
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((bytes.len() + 2) / 3 * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0] as u32;
        let b1 = if chunk.len() > 1 { chunk[1] as u32 } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] as u32 } else { 0 };
        let n  = (b0 << 16) | (b1 << 8) | b2;
        out.push(T[((n >> 18) & 63) as usize] as char);
        out.push(T[((n >> 12) & 63) as usize] as char);
        out.push(if chunk.len() > 1 { T[((n >>  6) & 63) as usize] as char } else { '=' });
        out.push(if chunk.len() > 2 { T[( n        & 63) as usize] as char } else { '=' });
    }
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// DALL-E 3
// ─────────────────────────────────────────────────────────────────────────────

fn generate_image_dalle(prompt: &str, api_key: &str, size: &str) -> Result<String, String> {
    let size_str = match size.to_lowercase().as_str() {
        "landscape" => "1792x1024",
        "portrait"  => "1024x1792",
        _           => "1024x1024",
    };

    let body = format!(
        r#"{{"model":"dall-e-3","prompt":{},"n":1,"size":"{}","response_format":"url","quality":"standard"}}"#,
        json_escape(prompt), size_str
    );

    let raw = curl_post(
        "https://api.openai.com/v1/images/generations",
        &[
            format!("Authorization: Bearer {}", api_key),
            "Content-Type: application/json".to_string(),
        ],
        &body, 60,
    )?;

    if raw.contains("\"error\"") {
        let msg = extract_json_str(&raw, "message")
            .unwrap_or_else(|| raw[..raw.len().min(200)].to_string());
        return Err(format!("OpenAI: {}", msg));
    }

    let url = extract_json_str(&raw, "url")
        .ok_or_else(|| format!("Cannot parse DALL-E response: {}", &raw[..raw.len().min(200)]))?;

    let revised = extract_json_str(&raw, "revised_prompt").unwrap_or_default();
    let note = if !revised.is_empty() && revised != prompt {
        format!("\n\n*Revised: {}*", &revised[..revised.len().min(200)])
    } else { String::new() };

    Ok(format!(
        "## 🖼 Image Generated\n\n\
         **[VIEW IMAGE]({url})**\n\n\
         `{url}`{note}\n\n\
         > DALL-E 3 · {size_str} · via Kala"
    ))
}

// ─────────────────────────────────────────────────────────────────────────────
// Stability AI SDXL
// ─────────────────────────────────────────────────────────────────────────────

fn generate_image_stability(prompt: &str, api_key: &str, size: &str) -> Result<String, String> {
    let (w, h): (u32, u32) = match size.to_lowercase().as_str() {
        "landscape" => (1344, 768),
        "portrait"  => (768, 1344),
        "hd"        => (1536, 1536),
        _           => (1024, 1024),
    };

    let body = format!(
        r#"{{"text_prompts":[{{"text":{},"weight":1}}],"cfg_scale":7,"height":{},"width":{},"samples":1,"steps":30}}"#,
        json_escape(prompt), h, w
    );

    let raw = curl_post(
        "https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image",
        &[
            format!("Authorization: Bearer {}", api_key),
            "Content-Type: application/json".to_string(),
            "Accept: application/json".to_string(),
        ],
        &body, 90,
    )?;

    if raw.contains("\"message\"") && (raw.contains("error") || raw.contains("Error")) {
        let msg = extract_json_str(&raw, "message")
            .unwrap_or_else(|| raw[..raw.len().min(200)].to_string());
        return Err(msg);
    }

    let b64 = extract_json_str(&raw, "base64")
        .filter(|s| !s.is_empty())
        .ok_or_else(|| format!("Cannot parse Stability response: {}", &raw[..raw.len().min(200)]))?;

    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs()).unwrap_or(0);
    let filename = format!("kala_image_{}.png", ts);

    if let Ok(bytes) = base64_decode_to_bytes(&b64) {
        if std::fs::write(&filename, &bytes).is_ok() {
            return Ok(format!(
                "## 🖼 Image Generated\n\n\
                 Saved to: **`{}`** ({}×{}px)\n\n\
                 > Stability AI SDXL · via Kala",
                filename, w, h
            ));
        }
    }

    Ok(format!(
        "## 🖼 Image Generated\n\n\
         Image data received ({} base64 chars). Save manually:\n\
         ```\necho '{}...' | base64 -d > image.png\n```\n\n\
         > Stability AI · via Kala",
        b64.len(), &b64[..b64.len().min(60)]
    ))
}

// ─────────────────────────────────────────────────────────────────────────────
// Runway Gen-3 Alpha Turbo
// ─────────────────────────────────────────────────────────────────────────────

fn generate_video_runway(prompt: &str, api_key: &str, duration: &str) -> Result<String, String> {
    let secs: u32 = duration.parse().unwrap_or(5).min(10).max(5);

    let body = format!(
        r#"{{"taskType":"textToVideo","textToVideoModel":"gen3a_turbo","textToVideoRequest":{{"seconds":{},"text_prompt":{},"seed":null}}}}"#,
        secs, json_escape(prompt)
    );

    let raw = curl_post(
        "https://api.runwayml.com/v1/tasks",
        &[
            format!("Authorization: Bearer {}", api_key),
            "Content-Type: application/json".to_string(),
            "X-Runway-Version: 2024-11-06".to_string(),
        ],
        &body, 30,
    )?;

    if raw.contains("\"error\"") {
        let msg = extract_json_str(&raw, "message")
            .or_else(|| extract_json_str(&raw, "error"))
            .unwrap_or_else(|| raw[..raw.len().min(200)].to_string());
        return Err(msg);
    }

    let task_id = extract_json_str(&raw, "id").unwrap_or_default();
    let status  = extract_json_str(&raw, "status").unwrap_or_else(|| "PENDING".to_string());
    let url_opt = extract_json_str(&raw, "url");

    if let Some(url) = url_opt {
        Ok(format!(
            "## 🎬 Video Generated\n\n\
             **[WATCH VIDEO]({url})**\n\n\
             `{url}`\n\n\
             > {secs}s · Runway Gen-3 Alpha Turbo · via Kala"
        ))
    } else {
        Ok(format!(
            "## 🎬 Video Task Queued\n\n\
             **Task ID:** `{task_id}`  \n\
             **Status:** {status}\n\n\
             Runway is generating your **{secs}s** video. \
             Typically takes **30–90 seconds**.\n\n\
             Track it at: [app.runwayml.com](https://app.runwayml.com)\n\n\
             > Runway Gen-3 Alpha Turbo · via Kala",
            task_id = task_id, status = status, secs = secs
        ))
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// OFFLINE GUIDES
// ─────────────────────────────────────────────────────────────────────────────

pub fn offline_image_guide(prompt: &str, style: &str, error_ctx: &str) -> String {
    let enhanced = enhance_image_prompt(prompt, style);
    let error_note = if !error_ctx.is_empty() {
        format!("\n> ⚠️ *{}*\n\n", error_ctx)
    } else { String::new() };

    let p_short = &prompt[..prompt.len().min(60)];

    format!(
        "## 🖼 Image Generation\n\n\
         {error_note}\
         **Kala crafted this enhanced prompt for you:**\n\
         ```\n{enhanced}\n```\n\n\
         **Paste it into any of these tools:**\n\n\
         | Tool | Quality | Cost | Best for |\n\
         |------|---------|------|----------|\n\
         | **DALL-E 3** | ⭐⭐⭐⭐⭐ | $0.04/img | Photorealism, concepts |\n\
         | **Midjourney** | ⭐⭐⭐⭐⭐ | $10/mo | Artistic, cinematic |\n\
         | **Stable Diffusion** | ⭐⭐⭐⭐ | Free (local) | Full control, offline |\n\
         | **Adobe Firefly** | ⭐⭐⭐⭐ | Free tier | Commercial safe |\n\
         | **Ideogram v2** | ⭐⭐⭐⭐ | Free tier | Text in images |\n\n\
         **To generate images directly with Kala (zero copy-paste):**\n\
         ```killer\n\
         kala_set_llm(\"openai\", \"sk-your-openai-key\")\n\
         url = kala_generate_image(\"{p_short}\")\n\
         print(url)\n\
         ```\n\n\
         *Or set `OPENAI_API_KEY` environment variable — Kala picks it up automatically.*"
    )
}

pub fn offline_video_guide(prompt: &str, error_ctx: &str) -> String {
    let cinematic = enhance_video_prompt(prompt);
    let error_note = if !error_ctx.is_empty() {
        format!("\n> ⚠️ *{}*\n\n", error_ctx)
    } else { String::new() };

    let p_short = &prompt[..prompt.len().min(60)];

    format!(
        "## 🎬 Video Generation\n\n\
         {error_note}\
         **Kala crafted this cinematic prompt for you:**\n\
         ```\n{cinematic}\n```\n\n\
         **Best video generation tools right now:**\n\n\
         | Tool | Quality | Cost | Best for |\n\
         |------|---------|------|----------|\n\
         | **Runway Gen-3** | ⭐⭐⭐⭐⭐ | $15/mo | Cinematic quality |\n\
         | **Sora (OpenAI)** | ⭐⭐⭐⭐⭐ | ChatGPT+ | Realistic physics |\n\
         | **Kling 1.6** | ⭐⭐⭐⭐ | Free tier | Up to 30s videos |\n\
         | **Pika 2.0** | ⭐⭐⭐⭐ | Free tier | Fast turnaround |\n\
         | **Hailuo (MiniMax)** | ⭐⭐⭐⭐ | Free | Surreal / anime |\n\
         | **Stable Video Diffusion** | ⭐⭐⭐ | Free (local) | Full control |\n\n\
         **To generate video directly with Kala:**\n\
         ```killer\n\
         kala_set_llm(\"runway\", \"your-runway-api-key\")\n\
         result = kala_generate_video(\"{p_short}\", \"5\")\n\
         print(result)\n\
         ```\n\n\
         > 💡 The cinematic prompt above is optimised for AI video — use it as-is for best results."
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// PROMPT ENHANCEMENT
// ─────────────────────────────────────────────────────────────────────────────

pub fn enhance_image_prompt(prompt: &str, style: &str) -> String {
    let suffix = match style.to_lowercase().as_str() {
        "photorealistic" | "photo" | "realistic" =>
            ", photorealistic, 8K UHD, professional photography, sharp focus, natural lighting",
        "artistic" | "art" | "painting" =>
            ", digital painting, concept art, highly detailed, vibrant colors, artstation trending",
        "anime" =>
            ", anime style, studio ghibli inspired, smooth lines, vibrant colors, detailed background",
        "3d" | "render" =>
            ", 3D render, octane render, ray tracing, volumetric lighting, ultra-detailed",
        "sketch" | "drawing" =>
            ", pencil sketch, clean linework, professional illustration, detailed shading",
        "cinematic" =>
            ", cinematic lighting, movie still, anamorphic lens, dramatic atmosphere, award-winning",
        _ => {
            let p = prompt.to_lowercase();
            if p.contains("killer") || p.contains("code") || p.contains("circuit") {
                ", cyberpunk aesthetic, neon glowing circuits, dark background, ultra-detailed, 8K"
            } else if p.contains("portrait") || p.contains("person") || p.contains("face") {
                ", professional portrait, studio lighting, sharp focus, photorealistic, 8K"
            } else if p.contains("city") || p.contains("skyline") || p.contains("architecture") {
                ", architectural photography, dramatic lighting, 8K, sharp detail"
            } else if p.contains("nature") || p.contains("landscape") || p.contains("forest") {
                ", landscape photography, golden hour, 8K, HDR, National Geographic style"
            } else if p.contains("space") || p.contains("galaxy") || p.contains("nebula") {
                ", NASA photo quality, deep space, vibrant nebula colors, ultra-detailed, 8K"
            } else {
                ", highly detailed, professional quality, vibrant, sharp focus, 8K"
            }
        }
    };
    format!("{}{}", prompt, suffix)
}

pub fn enhance_video_prompt(prompt: &str) -> String {
    let p = prompt.to_lowercase();
    let camera = if p.contains("city") || p.contains("skyline") {
        "cinematic drone shot, slow aerial pan"
    } else if p.contains("person") || p.contains("character") || p.contains("human") {
        "medium shot, cinematic depth of field"
    } else if p.contains("nature") || p.contains("landscape") {
        "sweeping landscape shot, slow motion"
    } else {
        "smooth camera movement, cinematic"
    };

    format!("{}, {}, high quality, detailed, professional cinematography, smooth motion, 24fps",
        prompt, camera)
}

// ─────────────────────────────────────────────────────────────────────────────
// CONFIG
// ─────────────────────────────────────────────────────────────────────────────

pub fn get_gen_config() -> (String, String, String) {
    // Dedicated env vars take priority
    let runway_key    = std::env::var("RUNWAY_API_KEY").unwrap_or_default();
    let stability_key = std::env::var("STABILITY_API_KEY").unwrap_or_default();
    let openai_key    = std::env::var("OPENAI_API_KEY").unwrap_or_default();

    if !runway_key.is_empty()    { return ("runway".into(),    runway_key,    String::new()); }
    if !stability_key.is_empty() { return ("stability".into(), stability_key, String::new()); }
    if !openai_key.is_empty()    { return ("openai".into(),    openai_key,    "dall-e-3".into()); }

    // Fall back to khlm_polyglot config (set via kala_set_llm)
    let cfg = config().lock().unwrap();
    (cfg.llm_provider.clone(), cfg.llm_api_key.clone(), cfg.llm_model.clone())
}

// ─────────────────────────────────────────────────────────────────────────────
// UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

fn curl_post(url: &str, headers: &[String], body: &str, timeout_s: u64) -> Result<String, String> {
    if !url.starts_with("https://") {
        return Err(format!("URL must use HTTPS: {}", &url[..url.len().min(50)]));
    }
    let timeout_str = timeout_s.to_string();
    let mut args = vec!["-s", "--fail-with-body", "--max-time", &timeout_str, "-X", "POST", url];
    let header_args: Vec<String> = headers.iter()
        .flat_map(|h| vec!["-H".to_string(), h.clone()])
        .collect();
    let header_refs: Vec<&str> = header_args.iter().map(|s| s.as_str()).collect();
    args.extend_from_slice(&header_refs);
    args.extend_from_slice(&["-d", body]);

    let output = Command::new("curl").args(&args).output()
        .map_err(|e| format!("curl not found: {}", e))?;
    let stdout = String::from_utf8_lossy(&output.stdout).to_string();
    let stderr = String::from_utf8_lossy(&output.stderr).to_string();
    if stdout.is_empty() && !stderr.is_empty() {
        return Err(format!("curl: {}", stderr.trim()));
    }
    Ok(stdout)
}

fn json_escape(s: &str) -> String {
    format!("\"{}\"", s
        .replace('\\', "\\\\").replace('"', "\\\"")
        .replace('\n', "\\n").replace('\r', "\\r").replace('\t', "\\t"))
}

fn extract_json_str(json: &str, key: &str) -> Option<String> {
    let needle = format!("\"{}\":", key);
    let pos = json.find(&needle)?;
    let rest = json[pos + needle.len()..].trim_start();
    if !rest.starts_with('"') { return None; }
    let inner = &rest[1..];
    let mut result = String::new();
    let mut chars = inner.chars().peekable();
    loop {
        match chars.next()? {
            '\\' => match chars.next()? {
                '"'  => result.push('"'), '\\' => result.push('\\'),
                'n'  => result.push('\n'), 'r' => result.push('\r'),
                't'  => result.push('\t'), c   => { result.push('\\'); result.push(c); }
            },
            '"' => break,
            c   => result.push(c),
        }
    }
    Some(result)
}

fn base64_decode_to_bytes(s: &str) -> Result<Vec<u8>, ()> {
    const T: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut rev = [255u8; 256];
    for (i, &c) in T.iter().enumerate() { rev[c as usize] = i as u8; }

    let bytes: Vec<u8> = s.bytes().filter(|&b| b != b'=' && b != b'\n' && b != b'\r').collect();
    let mut out = Vec::with_capacity(bytes.len() * 3 / 4);
    let mut i = 0;
    while i + 3 < bytes.len() {
        let [a, b, c, d] = [rev[bytes[i] as usize], rev[bytes[i+1] as usize],
                            rev[bytes[i+2] as usize], rev[bytes[i+3] as usize]];
        if a == 255 || b == 255 { break; }
        out.push((a << 2) | (b >> 4));
        if c != 255 { out.push((b << 4) | (c >> 2)); }
        if d != 255 { out.push((c << 6) | d); }
        i += 4;
    }
    Ok(out)
}

fn get_str_arg(args: &[Value], idx: usize, name: &str) -> Result<String, VmError> {
    match args.get(idx) {
        Some(Value::Str(s)) => Ok(s.clone()),
        Some(_) => Err(VmError::runtime_error(format!("argument '{}' must be a string", name))),
        None    => Err(VmError::runtime_error(format!("missing argument '{}'", name))),
    }
}
