// Killer Language Runtime
function typeof__(value) {
  if (typeof value === 'boolean') return 'boolean';
  if (typeof value === 'number') return 'number';
  if (typeof value === 'string') return 'string';
  if (Array.isArray(value)) return 'array';
  if (value === null) return 'null';
  if (typeof value === 'object') return 'object';
  if (typeof value === 'function') return 'function';
  return 'object';
}

console.log("=== Test 1: typeof operator ===");
let x = 42;
console.log(typeof__(x));
let y = "hello";
console.log(typeof__(y));
let z = true;
console.log(typeof__(z));
let arr = [1, 2, 3];
console.log(typeof__(arr));
console.log("=== Test 2: Exponentiation ===");
let result1 = (2 ** 3);
console.log(result1);
let result2 = (5 ** 2);
console.log(result2);
console.log("=== Test 3: Math object ===");
console.log(Math.sqrt(16));
console.log(Math.abs((-10)));
console.log(Math.pow(2, 8));
console.log(Math.floor(3.7));
console.log(Math.ceil(3.2));
console.log(Math.round(3.5));
console.log(Math.min(5, 2, 8, 1));
console.log(Math.max(5, 2, 8, 1));
console.log("=== Test 4: Type conversion ===");
console.log(parseInt("42"));
console.log(parseFloat("3.14"));
console.log(String(42));
console.log(String(true));
console.log(Number("99"));
console.log(Number(false));
console.log(Boolean(1));
console.log(Boolean(0));
console.log(Boolean(""));
console.log(Boolean("hello"));
console.log("=== Test 5: String methods ===");
let text = "hello world";
console.log(text.startsWith("hello"));
console.log(text.endsWith("world"));
console.log(text.repeat(2));
let str = "5";
console.log(str.padStart(3, "0"));
console.log(str.padEnd(3, "0"));
console.log(text.slice(0, 5));
console.log("=== Test 6: Array methods ===");
let numbers = [1, 2, 3, 4, 5];
console.log(numbers.includes(3));
let result = numbers.concat([6, 7]);
console.log(result);
console.log("=== Test 7: Array indexOf ===");
let nums = [10, 20, 30, 40, 50];
let idx = nums.indexOf(30);
console.log(idx);
console.log("=== All tests completed ===");